# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: Windows
  pool:
    vmImage: 'windows-latest'

  steps:
  - checkout: self
    submodules: true

  - task: CMake@1
    displayName: 'Cmake ..'
    inputs:
      cmakeArgs: '..'

  - task: VSBuild@1
    displayName: 'Project Build: ${BuildConfiguration}'
    inputs:
      solution: '**.sln'
      configuration: $(BuildConfiguration)


