# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: Windows
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: CMake@1
    displayName: 'Cmake ..'
    inputs:
      cmakeArgs: '..'

  - task: CMake@1
    displayName: 'Cmake Debug Build'
    inputs:
      cmakeArgs: '--build . --config Debug'

